blank_issues_enabled: true
contact_links:
  - name: ðŸ“š Documentation
    url: https://github.com/J0kt/KITCHEN_GURU/blob/main/README.md
    about: Consultez la documentation du projet

  - name: ðŸ’¬ Discussions
    url: https://github.com/J0kt/KITCHEN_GURU/discussions
    about: Posez des questions et discutez avec la communautÃ©
